# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96c9d85baeda62f2f6911f3a7153e2bea2060c826d51615d317aa8f2484bd72a10cf29a24e3fbeefd9463503d1a678975c2ac75097a5ac1cbdc4906b40c4d1f9

test:
  secret_key_base: 6c46d0bebf56616a615fa174797dd3218b6993245f9e0df094bc386911c71b18a484ccdce8b37842895204408d252667c7dfe604dc713bcab856c065f5815752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
